export const YOGA_POSES = [
    {
        name: "Siddhasana",
        description: "Pozycja siedząca z nogami skrzyżowanymi. Jest to druga najważniejsza, obok Siddhasany, pozycja do medytacji.",
        steps: [
            "usiądź płasko na ziemi z nogami wyprostowanymi i połączonymi, Dandasana",
            "zginając nogi przełóż je bokiem i usiądź na stopach.",
            "stopy wyciągnięte do tyłu a pięty dokładnie pod guzami kulszowymi (kośćmi pośladków)",
            "rozluźnij nogi całkowicie",
            "miednica ustawiona pionowo a dolne plecy lekko wklęsłe",
            "otwórz klatkę piersiową podnosząc mostek cofając barki,",
            "twarz ustaw pionowo i wyciągnij czubek głowy,",
            "grzbiety rąk połóż na udach blisko bioder",
            "utrzymując proste plecy rozluźnij się całkowicie",
            "pozostań w pozycji 30  do 60 sek.",
        ],
        benefits: ["rozluźnia i relaksuje nogi",
            " rozciąga stawy skokowe",
            "uelastycznia kolana",
            "kształtuje sylwetkę z otwartą klatką piersiową",
            "uspokaja i pogłębia oddech",
            " wycisza umysł"],
        tip: "Jeśli odczujesz w stopach (grzbietach stóp) bardzo bolesne rozciąganie, które uniemożliwi ci wykonanie pozycji, zroluj koc lub ręcznik i podłóż pod kostki stóp. Złagodzi to wyprost stawu skokowego i zmniejszy intensywność rozciągania. Z czasem będzie można zmniejszyć wałek lub zrezygnować z niego. Jeśli nie możesz zgiąć kolan na tyle aby usiąść na piętach lub po wejściu w pozycję pojawiający się w kolanach ból nie pozwala ci się rozluźnić włóż odpowiedniej grubości koc między pięty a pośladki.",
        level: 0
    },
    {
        name: "Padmasana",
        description: "Pozycja siedząca z nogami skrzyżowanymi. Jest to druga najważniejsza, obok Siddhasany, pozycja do medytacji.",
        steps: ["usiądź płasko na ziemi z nogami wyprostowanymi i połączonymi – Dandasana,",
            "zegnij i skrzyżuj nogi do Swastikasany, najpierw zginając lewą nogę, następnie prawą,",
            "wysuń prawą stopę spod lewego kolana i pozwól aby lewe kolano opadło na ziemię,",
            "prawe kolano powinno opaść na lewą stopę,",
            "kiedy kolana opadną chwyć prawą stopę i wsuń ją na szczyt lewego uda,",
            "to jest Ardha padmasana (pół lotos) – opanowanie tej pozycji jest konieczne zanim przejdziesz do kolejnego etapu,",
            "następnie wysuń lewą stopę spod prawego kolana i pozwól aby kolano opadło na ziemię,",
            "gdy prawe kolano opadnie na ziemię, chwyć lewą stopę i wsuń na szczyt prawego uda,",
            "połóż grzbiety dłoni na udach,",
            "wyciągnij do góry tułów i kręgosłup,",
            "otwórz klatkę piersiową unosząc mostek do góry,",
            "rozluźnij brzuch i podbrzusze,",
            "wykonaj pozycję, zmieniając splot nóg,",
            "początkowo pozostawaj w asanie po 30 sek. na stronę, stopniowo wydłużając ten czas."]
        ,
        benefits: ["relaksuje nogi i biodra,",
            " zapewnia elastyczność stawów biodrowych,",
            "relaksuje brzuch i podbrzusze,",
            "uspokaja i pogłębia oddech,",
            "wycisza umysł,",
            "doskonała pozycja do medytacji."],
        tip: "To sztywność bioder a nie kolan jest przeszkodą w wykonaniu lotosu. Jeśli kolana nie opadają na ziemię nie próbuj forsować pozycji – to może prowadzić do nadwyrężenia kolan. Ćwicz wtedy wszystkie inne pozycje siedzące i stojące, przygotowując biodra do lotosu. Spróbuj też usiąść nieco wyżej wkładając 1, 2 koce pod pośladki, co pomaga opaść kolanom i wyprostować plecy.",
        level: 4,
    },
    {
        name: "Vajrasana",
        description: "vajra oznacza piorun, błyskawicę. Jest  to siad ze stopami pod pośladkami.",
        steps: [
            " usiądź płasko na ziemi z nogami wyprostowanymi i połączonymi, Dandasana",
            "zginając nogi przełóż je bokiem i usiądź na stopach.",
            "stopy wyciągnięte do tyłu a pięty dokładnie pod guzami kulszowymi (kośćmi pośladków)",
            "rozluźnij nogi całkowicie",
            " miednica ustawiona pionowo a dolne plecy lekko wklęsłe",
            "otwórz klatkę piersiową podnosząc mostek cofając barki,",
            "twarz ustaw pionowo i wyciągnij czubek głowy,",
            "grzbiety rąk połóż na udach blisko bioder",
            "utrzymując proste plecy rozluźnij się całkowicie",
            "pozostań w pozycji 30  do 60 sek. ",
        ],
        benefits: [
            "rozluźnia i relaksuje nogi",
            "rozciąga stawy skokowe",
            "uelastycznia kolana",
            "kształtuje sylwetkę z otwartą klatką piersiową",
            "uspokaja i pogłębia oddech,",
            "wycisza umysł"
        ],
        tip: "Jeśli odczujesz w stopach (grzbietach stóp) bardzo bolesne rozciąganie, które uniemożliwi ci wykonanie pozycji, zroluj koc lub ręcznik i podłóż pod kostki stóp. Złagodzi to wyprost stawu skokowego i zmniejszy intensywność rozciągania. Z czasem będzie można zmniejszyć wałek lub zrezygnować z niego. Jeśli nie możesz zgiąć kolan na tyle aby usiąść na piętach lub po wejściu w pozycję pojawiający się w kolanach ból nie pozwala ci się rozluźnić włóż odpowiedniej grubości koc między pięty a pośladki.",
        level: 0
    }
]